### ISSUE TITLE
Étape 1 : Analyse

### ISSUE THREAD

**Issue by EricFunes** [yoandimov/FriendZone#1]
Objectifs spécifiques :

- Concevoir l’architecture d’une application locale et web à partir d'une étude des besoins.

**Contenu :**
- [x] Modèle de la base de données
- [x] Diagramme de cas d'utilisation
- [x] Analyse et spécification des fonctionnalités d’une application
- [x] Gestion d’un échéancier de travail
- [x] Diagramme de classe UML
- [x] Diagramme de séquence
- [x] Prototype Android
- [x] Prototype web
- [x] Cahier des charges

**Comment by SidNewfel** [comment]
Analyse et spécification des fonctionnalités d’une application : 
Spécification et fonctionnalités
Enregistrement (inscription)
Connection (Authentification)
Création de poste
Commenter les postes
Liker les postes (mettre un j’aime)
Acceder a tous ses postes
Pour l’application Android critère spécifique :
• Un écran permettant à l’utilisateur de s’authentifier 
• Un minimum de 5 pages écrans différentes.
• Utilisation du Data Binding.
• Un Navigation Drawer.
• Un écran de configuration (Preferences).
• Au moins un écran avec une configuration différente en fonction de son orientation (Fragment).
• Des appels à un serveur http.
• Une base de données.
• Sauvegarde et accès à des fichiers.
• Un écran comportant un Action mode.
• Au moins une notification.
• Au moins un accès au matériel (Caméra, Localisation, Bluetooth, etc).
• Gestion adéquate du cycle de vie des activités et fragments.
• Votre application doit être publiée sur Google Play.
